# Colors (Adwaita Dark)
# Based on Mofiqul/adwaita.nvim palette

# Default colors
[colors.primary]
background = '#1D1D20'
foreground = '#DEDDDA'

# Normal colors
[colors.normal]
black   = '#1D1D20'
red     = '#ED333B'
green   = '#57E389'
yellow  = '#FF7800'
blue    = '#62A0EA'
magenta = '#9141AC'
cyan    = '#5BC8AF'
white   = '#DEDDDA'

# Bright colors
[colors.bright]
black   = '#9A9996'
red     = '#F66151'
green   = '#8FF0A4'
yellow  = '#FFA348'
blue    = '#99C1F1'
magenta = '#DC8ADD'
cyan    = '#93DDC2'
white   = '#F6F5F4'
