---
- name: Retrieve latest release information from github
  ansible.builtin.uri:
    url: https://api.github.com/repos/ryanoasis/nerd-fonts/releases/latest
    method: GET
    return_content: true
  register: nerd_fonts_github_response

- name: Select download url for JetBrainsMono from json response
  ansible.builtin.set_fact:
    jetbrains_mono_download_url: "{{ 0 | extract(nerd_fonts_github_response.json | community.general.json_query(url_query)) }}"
  vars:
    url_query: assets[?name=='JetBrainsMono.tar.xz'].browser_download_url

- name: Download JetBrainsMono Nerd Font
  ansible.builtin.get_url:
    url: "{{ jetbrains_mono_download_url }}"
    dest: /tmp/JetBrainsMono.tar.xz
    mode: "0644"
  register: download_status

- name: Create fonts directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/share/fonts/JetBrainsMonoNerdFont"
    state: directory
    mode: '0755'

- name: Remove existing font files
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/share/fonts/JetBrainsMonoNerdFont"
    state: absent
  when: download_status.changed # Remove only if the archive was re-downloaded

- name: Recreate fonts directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/share/fonts/JetBrainsMonoNerdFont"
    state: directory
    mode: '0755'
  when: download_status.changed # Create only if the archive was re-downloaded

- name: Extract JetBrainsMono fonts
  ansible.builtin.unarchive:
    src: /tmp/JetBrainsMono.tar.xz
    dest: "{{ ansible_env.HOME }}/.local/share/fonts/JetBrainsMonoNerdFont/"
    remote_src: yes
  when: download_status.changed # Extract only if the archive was re-downloaded

- name: Rebuild font cache
  ansible.builtin.command:
    cmd: fc-cache -f -v
  when: download_status.changed # Rebuild only if fonts were updated

- name: Clean up downloaded archive
  ansible.builtin.file:
    path: /tmp/JetBrainsMono.tar.xz
    state: absent
