---
- name: Retrieve latest release information from github
  ansible.builtin.uri:
    url: https://api.github.com/repos/jesseduffield/lazygit/releases/latest
    method: GET
    return_content: true
  register: lazygit_github_response

- name: Select download url from json response
  ansible.builtin.set_fact:
    lazygit_download_url: "{{ 0 | extract(lazygit_github_response.json | community.general.json_query(url_query)) }}"
  vars:
    url_query: assets[?ends_with(browser_download_url,'linux_x86_64.tar.gz')].browser_download_url

- name: Download lazygit tarball
  ansible.builtin.get_url:
    url: "{{ lazygit_download_url }}"
    dest: "/tmp/lazygit.tar.gz"
    mode: "0644"
  register: download_status

- name: Remove existing lazygit installation
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/opt/lazygit/"
    state: absent
  when: download_status.changed # Remove only if the tarball was re-downloaded

- name: Create lazygit directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/opt/lazygit"
    state: directory
  when: download_status.changed # Create only if the tarball was re-downloaded

- name: Extract lazygit files
  ansible.builtin.unarchive:
    src: "/tmp/lazygit.tar.gz"
    dest: "{{ ansible_env.HOME }}/.local/opt/lazygit/"
    remote_src: yes
  when: download_status.changed # Extract only if the tarball was re-downloaded

- name: Create symlink to binary
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/.local/opt/lazygit/lazygit"
    dest: "{{ ansible_env.HOME }}/.local/bin/lazygit"
    state: link
    force: yes

- name: Clean up downloaded tarball
  ansible.builtin.file:
    path: "/tmp/lazygit.tar.gz"
    state: absent
